#ifndef _LJW_TREELIB_EC_H_
#define _LJW_TREELIB_EC_H_
#define TREELIBBSTARGV 1
#define TREELIBBSTEMPTY 2
#define TREELIBBSTICMP 3
#define TREELIBBSTDNF 4
#define TREELIBBSTDUP 5
#define TREELIBBSTITOD 6
#define TREELIBRBTARGV 7
#define TREELIBRBTICMP 8
#define TREELIBRBTDUP 9
#define TREELIBRBTEMPTY 10
#define TREELIBRBTDNF 11
#define TREELIBRBTITOD 12
#define TREELIBBTARGV 13
#define TREELIBBTOBD 14
#define TREELIBBTDNF 15
#define TREELIBBTDUP 16
#endif
